import { generateText } from "../ai/llmClient.js";
import { interviewResearchSchema } from "../ai/schemas.js";
import { interviewResearchPrompt } from "./researchPrompts.js";
import { searchWeb, WebSearchResult } from "./searchWeb.js";

const PREFERRED_DOMAINS = [
  "glassdoor.com",
  "reddit.com",
  "jointaro.com",
  "medium.com",
  "linkedin.com",
  "leetcode.com",
];

const searchQueries = (
  companyName: string,
  role: string
): string[] => {
  return [
    `"${companyName}" "${role}" interview experience`,
    `"${companyName}" "${role}" interview questions candidate experience`,
    `"${companyName}" "${role}" hiring process technical interview`,
  ];
};

const isRelevantResult = (
  result: WebSearchResult,
  companyName: string,
  role: string
): boolean => {
  const text = `
    ${result.title}
    ${result.url}
    ${result.content}
  `.toLowerCase();

  const company = companyName.toLowerCase();
  const roleWords = role
    .toLowerCase()
    .split(/\s+/)
    .filter((word) => word.length > 2);

  const hasCompany = text.includes(company);

  const hasRole =
    roleWords.length === 0 ||
    roleWords.some((word) => text.includes(word));

  return hasCompany && hasRole;
};

const isPreferredSource = (url: string): boolean => {
  return PREFERRED_DOMAINS.some((domain) =>
    url.toLowerCase().includes(domain)
  );
};

const deduplicateResults = (
  results: WebSearchResult[]
): WebSearchResult[] => {
  const seen = new Set<string>();

  return results.filter((result) => {
    try {
      const normalizedUrl = new URL(result.url);

      normalizedUrl.hash = "";

      const key = normalizedUrl.toString();

      if (seen.has(key)) {
        return false;
      }

      seen.add(key);

      return true;
    } catch {
      return false;
    }
  });
};

export const researchInterview = async (
  companyName: string,
  role: string
) => {
  const queries = searchQueries(companyName, role);

  const allResults: WebSearchResult[] = [];

  const gaps: string[] = [];

  for (const query of queries) {
    try {
      const results = await searchWeb(query);

      allResults.push(...results);
    } catch (error) {
      console.error("Interview search failed:", error);

      gaps.push(`Search failed for query: ${query}`);
    }
  }

  const uniqueResults = deduplicateResults(allResults);

  const relevantResults = uniqueResults.filter((result) =>
    isRelevantResult(result, companyName, role)
  );

  const sortedResults = relevantResults.sort((a, b) => {
    const aPreferred = isPreferredSource(a.url) ? 1 : 0;
    const bPreferred = isPreferredSource(b.url) ? 1 : 0;

    return bPreferred - aPreferred;
  });

  const topResults = sortedResults.slice(0, 10);

  if (topResults.length === 0) {
    gaps.push(
      "No reliable public interview discussion was found for this company and role."
    );

    return {
      process: [],
      common_topics: [],
      reported_questions: [],
      sources: [],
      gaps,
    };
  }

  const searchContext = topResults
    .map(
      (result, index) => `
RESULT ${index + 1}

TITLE:
${result.title}

URL:
${result.url}

CONTENT:
${result.content}
`
    )
    .join("\n");

  const prompt = interviewResearchPrompt(
    companyName,
    role,
    searchContext
  );

  const rawResponse = await generateText(prompt);

  let parsed: unknown;

  try {
    parsed = JSON.parse(rawResponse);
  } catch {
    throw new Error(
      "Gemini returned invalid JSON for interview research"
    );
  }

  const validated =
    interviewResearchSchema.safeParse(parsed);

  if (!validated.success) {
    console.error(
      "Interview research validation error:",
      validated.error
    );

    throw new Error(
      "Invalid interview research structure returned by Gemini"
    );
  }

  const research = validated.data;

  const sourceUrls = topResults.map(
    (result) => result.url
  );

  return {
    ...research,

    // Sources are controlled by our application,
    // not generated by Gemini.
    sources: sourceUrls,

    gaps: [
      ...gaps,
      ...research.gaps,
    ],
  };
};